### PR TITLE
[ENH] [BUG] Improving Runtime of Elastic Ensemble by 20x (by fixing the closure issue)

### PR DESCRIPTION
**Pull request by patrickzib**
Elastic Ensemble was among the slowest methods in CI. 

The root cause are closures in numba, which are recompiled upon every call.

This PR fixes the numba closure issue.

### CODE REVIEW

**Comment by patrickzib** [comment]
Removing the single njit here, causes a runtime improve of 20-30x for me locally.

https://github.com/scikit-time/scikit-time/blob/c73f14422e38abbdb9f541145e461d272a10c312/sktime/distances/_distance.py#L1951

**Comment by patrickzib** [comment]
> see this #141

Unfortunately, the distance factory is already part of the code in ElacstocEnsemble

**Comment by patrickzib** [comment]
This PR fixes the issue.

Before (Windows 3.9) :
image


After (Windows 3.9):
image


Elastic Ensemble is no longer in the list of slowest 10 methods.

**Comment by chrisholder** [comment]
Ill test EE classifier on the new distances branch and check the performance now though.

**Comment by patrickzib** [comment]
Hi @chrisholder , maybe this is a misconception :) The returned function is still numba-compiled. But the method to return the numba-compiled function is not. This is why it is not breaking anything and we do not have the closure problem any longer

**Comment by patrickzib** [comment]
I.e. `callable(_x, _y)` is still numba-compiled. But the method to return this callable is not any longer.

**Comment by chrisholder** [comment]
Sorry, i dont think I understand your code then.

What is this line doing:

    global dist_callable

**Comment by chrisholder** [comment]
But this

`dist_callable = distance_factory(x, y, metric="dtw")`

This no longer would be a numba distance?

**Comment by patrickzib** [comment]
> But this
> 
> `dist_callable = distance_factory(x, y, metric="dtw")`
> 
> This no longer would be a numba distance?

Were is or called like this?

**Comment by patrickzib** [comment]
> Ill test EE classifier on the new distances branch and check the performance now though.

I am happy to go for your changes, once ready. In the mean time, we could go for this small change though, as it seems to work just fine?

**Comment by chrisholder** [comment]
So lets say I had

```
def example(x, y):
    # With this change this gives a python function
    dist = distance_factory(x, y, metric="dtw")
    
    @njit()
    def some_numba_function(ts1, ts2):
        return dist(ts1, ts2)
```

From my understanding (and sorry if im wrong!) the change would cause this to throw an error because you cant call a non numba function from inside a numba function.

**Comment by chrisholder** [comment]
Sure im happy for this to go in since there are changes coming soon for the distance module and this in the mean time will greatly improve development speed!

**Review by chrisholder — APPROVED** [review]
New changes for distance module coming soon but this is a good fix to improve dev speed for the package while waiting for those changes.

**Comment by patrickzib** [comment]
> My opinion on it if you want speed (which I think we do) you just say give it a 2d array or it wont work and then you could delete this additional compilation:
> 
> ```
> @njit()
>   def dist_callable(x: np.ndarray, y: np.ndarray):
>       _x = _numba_to_timeseries(x)
>       _y = _numba_to_timeseries(y)
>       return callable(_x, _y)
> ```
> 
> and just return callable instead

sure! Totally agree. This was not adressed by this PR though, which only solves the numba compilation of the closure on every call as done in EE

**Comment by patrickzib** [comment]
> So lets say I had
> 
> ```
> def example(x, y):
>     # With this change this gives a python function
>     dist = distance_factory(x, y, metric="dtw")
>     
>     @njit()
>     def some_numba_function(ts1, ts2):
>         return dist(ts1, ts2)
> ```


Thank you for approval. Will wait for merging to check this use case. I am interested in the result, too, bit do not have a PC right now :)

Would be great to hear from the results of EE in your branch, too.

**Pull request merged**
