### PR TITLE
[MNT] Remove Python 3.7 support

### LINKED ISSUE #84: [ENH] Deprecate Python 3.7 and bump scikit-learn version
Some estimators dont support Python 3.7 anymore, we should think about deprecating it. Also newer `scikit-learn>=1.1.0` has no Python 3.7 anymore.

Probably we can bump then `scikit-learn>=1.1.0` and possibly also other dependencies to require a higher version.

### PR DESCRIPTION
**Pull request by aiwalter**
closes #84

### CODE REVIEW

**Comment by lmmentel** [comment]
Maybe it's a bit premature to drop support before official EOL. How about prepping a PR and merging closer to actual EOL?

**Comment by MatthewMiddlehurst** [comment]
sklearn dropped 3.7 back in v1.1.0. I think now would be as good a time as any.

**Comment by lmmentel** [comment]
I guess by the time we release we might be quite close to py3.7 EOL so it makes sense.

**Review by lmmentel — APPROVED** [review]
:+1:

**Pull request merged**
