### PR TITLE
Remove duplicate function 

### LINKED ISSUE #119: [BUG] Remove duplicate function in classification/tests/test_base.py
somehow, we have written the same function twice :) They are both used so pick one, change the uses and get rid of the other. 
(unless I am missing something @MatthewMiddlehurst )
image

### PR DESCRIPTION
**Pull request by scorcism**
[BUG] Remove duplicate function in classification/tests/test_base.py #119

#### Reference Issues/PRs
Fixes #119 [BUG] Remove duplicate function in classification/tests/test_base.py 

#### What does this implement/fix? Explain your changes.
Removed a duplicate function inside classification/tests/test_base.py

#### Does your contribution introduce a new dependency? If yes, which one?
No

##### For all contributions
- [x] I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/.all-contributorsrc).
- [ ] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/sktime/sktime/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [x] The PR title starts with either [ENH], [MNT], [DOC], or [BUG] indicating whether the PR topic is related to enhancement, maintenance, documentation, or bug.

### CODE REVIEW

**Comment by scorcism** [comment]
I don't know why this gave so many failed test results :(

**Review by TonyBagnall — CHANGES_REQUESTED** [review]
hi, you will need to change the calls to _create_nested_dataframe too
# y:np.array and np.Series
    test_X3 = _create_nested_dataframe(5, 1, 10)
    test_X4 = _create_nested_dataframe(5, 3, 10)

**Comment by TonyBagnall** [comment]
if you look here

**Comment by scorcism** [comment]
Hey @TonyBagnall, The functions which are duplicate have different names and i removed the function which text_X3 and test_X4 uses : https://imgur.com/HHwMhr6.png

**Comment by scorcism** [comment]
I have made the changes

**Comment by TonyBagnall** [comment]
you need to keep _create_example_dataframe, delete _create_nested_dataframe and then change the calls to _create_nested_dataframe so that _create_example_dataframe  is called instead.

**Comment by scorcism** [comment]
so, basically I have to change calls for `_create_nested_dataframe` **to** `_create_example_dataframe`

**Pull request merged**
