### PR TITLE
[ENH] Remove fit_predict_proba from Base-Class, Use sklearn cross_val_predict instead

### PR DESCRIPTION
**Pull request by patrickzib**
This removes fit_predict_proba from the Base-Class in Classification.

The same functionality is present in sklearn, called `cross_val_predict`, and has a much simpler api:
https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.cross_val_predict.html

Here is a check, that it gives the same results:
```python
    X_train, y_train = load_gunpoint(split="train", return_type="numpy2d")

    # train weasel
    weasel = WEASEL(random_state=0)
    weasel.fit(X_train, y_train)
    predictions1 = weasel.fit_predict(X_train, y_train, cv=5)
    print("Sktime Predictions\n", predictions1)

    from sklearn.model_selection import cross_val_score
    score = cross_val_score(WEASEL(random_state=0), X_train, y_train, cv=5)
    print("Sklearn Score", score)

    from sklearn.model_selection import cross_val_predict
    predictions2 = cross_val_predict(WEASEL(random_state=0), X_train, y_train, cv=5)
    print("Sklearn Predictions:\n", predictions2)
    print("Predictions Equal:\n", (predictions2 == predictions1).all())
```

> [...]
> Predictions Equal: True

### CODE REVIEW

**Comment by TonyBagnall** [comment]
I agree with this. I'd be interested in a timing comparison on a big data set .... Have you checked the docs, notebooks, API?

**Comment by TonyBagnall** [comment]
also there is a whole testing set for fit_predict, with hundreds of calls and some are slow. For example, this is in top 20 

30.04s call     sktime/tests/test_all_estimators.py::TestAllEstimators::test_fit_returns_self[WEASEL-ClassifierFitPredict] 

if looks like it calls return self on fit and fit_predict, so thats an extra hundred odd calls to fit and predict just on this one tiny test. God knows how many others there are. so this is another great reason to ditch fit_predict, but the testing code will need adjusting

**Comment by patrickzib** [comment]
Yes, I have removed the tests for `fit_predict()`.

My Benchmark results:

```
CinCECGTorso
Sktime fit_predict() 8.66152286529541
Sklearn cross_val_score 5.2489988803863525

Beef
Sktime fit_predict() 2.70009708404541
Sklearn cross_val_score 1.8755667209625244
```

Sklearn is faster - I guess, as it does not do any conversion to DataFrames.


```python
    X_train, y_train = load_UCR_UEA_dataset(
        "Beef", split="train", return_type="numpy2d"
    )

    start = time.time()
    weasel = WEASEL(random_state=0)
    predictions1 = weasel.fit_predict(X_train, y_train, cv=5)
    print("Sktime fit_predict()", time.time() - start)

    start = time.time()
    predictions2 = cross_val_predict(
        WEASEL(random_state=0), X_train, y_train, cv=5, n_jobs=1
    )
    print("Sklearn cross_val_score", time.time() - start)
```

**Comment by patrickzib** [comment]
There seem to be only auto-generated comments from the class. Once removed, these will be removed, too :)

**Comment by patrickzib** [comment]
> StarLightCurve:
> Sktime fit_predict() 120.08437204360962
> Sklearn cross_val_score 96.24473810195923

~25% improve without our self-implemented method.

**Comment by TonyBagnall** [comment]
interesting, thanks. I am happy with this change but lets wait a couple of days to merge to give others a chance to express an opinion. It would be good to have some run time benchmarking tools vs other implementations, I feel fast run time is another thing we could differentiate on from the old sktime

**Review by MatthewMiddlehurst — APPROVED** [review]
I am fine with this interface change.

**Pull request merged**
