### PR TITLE
[ENH] Changed grid search parallelization to use backend param from e…

### PR DESCRIPTION
**Pull request by aiwalter**
#### Reference Issues/PRs
https://github.com/sktime/sktime/pull/3898

@topher-lo finally finishing this up in our new repo!

### CODE REVIEW

**Review by topher-lo — APPROVED** [review]
LGTM 👍

**Review by GuzalBulatova — APPROVED** [review]
Great job @aiwalter !

**Comment by aiwalter** [comment]
@topher-lo do you know whats the difference to use `dask` sparately compared to this: https://joblib.readthedocs.io/en/latest/auto_examples/parallel/distributed_backend_simple.html

Seems `joblib` has an interface to it?

**Review by patrickzib — COMMENTED** [review]
a simple hint. no blocker

**Comment by topher-lo** [comment]
> @topher-lo do you know whats the difference to use `dask` sparately compared to this: https://joblib.readthedocs.io/en/latest/auto_examples/parallel/distributed_backend_simple.html
> 
> 
> 
> Seems `joblib` has an interface to it?

The "pure" Dask implementation is slightly faster and more stable from my own internal tests. Joblib uses Dask futures which parallelises eagerly, the custom Dask implementation uses delayed (ie the computation graph is build first then run).

**Pull request merged**
