### PR TITLE
[ENH] Add `prefer="threads"` to classification `Parallel` usage

### PR DESCRIPTION
**Pull request by MatthewMiddlehurst**
Contents of https://github.com/sktime/sktime/pull/3879

Related to #61.

### CODE REVIEW

**Review by patrickzib — DISMISSED** [review]
Thank you!

**Comment by MatthewMiddlehurst** [comment]
Just a lot going on. Can only run so many actions at once. Big downside of having 4 hour test runs.

**Comment by patrickzib** [comment]
> B028 No explicit stacklevel keyword argument found. The warn method from the warnings module uses a stacklevel of 1 by default. This will only show a stack trace for the line on which the warn method is called. It is therefore recommended to use a stacklevel of 2 or greater to provide more information to the user.

I saw this, too, on my code.

It has to be:

```python

warnings.warn(
                ... , stacklevel=1
            )
```

Wonder if this check is new?

**Review by patrickzib — DISMISSED** [review]
Well done!

**Review by lmmentel — APPROVED** [review]

**Review by patrickzib — APPROVED** [review]

**Pull request merged**
