### PR TITLE
[MNT] Bump versions of pre-commit checks 

### PR DESCRIPTION
**Pull request by lmmentel**
#### What does this implement/fix? Explain your changes.

Bumping version of the packages providing pere-commit checks.

### CODE REVIEW

**Comment by aiwalter** [comment]
I am having issues with the `isort` on windows, is this fixing it? But probably you are not Windows user? 😞

**Review by aiwalter — APPROVED** [review]

**Comment by lmmentel** [comment]
Probably not since `isort` is the only check the I didn't bump the version for since it was already up to date.

**Comment by aiwalter** [comment]
btw on Windows getting this now:
```
ERROR: Could not find a version that satisfies the requirement poetry-core>=1.0.0 (from versions: none)  
      ERROR: No matching distribution found for poetry-core>=1.0.0
      [end of output]
```

**Comment by lmmentel** [comment]
Under what circumstances are you seeing that error?

**Pull request merged**
