### PR TITLE
refactor BaseClassifier attribute _threads_to_use to _n_jobs

### PR DESCRIPTION
**Pull request by TonyBagnall**
refactor the the base classifier attribute _threads_to_use to _n_jobs in order to conform to the general style.

### CODE REVIEW

**Review by patrickzib — COMMENTED** [review]
I am in favor of this change. However, I do not quite understand, when to use `self._n_jobs` and `self.n_jobs` in classifiers.

As I understand it now:

when we call fit() it will set  

```python
self._threads_to_use = check_n_jobs(self.n_jobs)
```

Thus, from there on, we should always use self._n_jobs instead of self.n_jobs?

(there are a couple of uses of `self.n_jobs` (without underscore) in the classifiers. Thus, maybe these should be changed, too)

**Comment by patrickzib** [comment]
Classes still using Parallel(n_jobs=self.n_jobs) (without underscore):

_tsf.py
_boss.py
_rise.py
_ensemble.py
_muse.py
_weasel.py
clear_sky.py


Maybe I missed some ...

**Comment by TonyBagnall** [comment]
> Classes still using Parallel(n_jobs=self.n_jobs) (without underscore):
> 
> _tsf.py _boss.py _rise.py _ensemble.py _muse.py _weasel.py clear_sky.py
> 
> Maybe I missed some ...

So I guess this is why it hasnt been changed .... I agree that they should all use _n_jobs, but I think I will keep it to classifiers for now, not sure what clear_sky.py is

**Comment by TonyBagnall** [comment]
I'm not touching _tsf as I had to hack it to work, it needs redoing. This refactor is more complex that I imagined. 
image

**Comment by TonyBagnall** [comment]
I'm going to close this for now and just raise the issue https://github.com/scikit-time/scikit-time/issues/102

**Pull request closed without merging**
